export const V_STUBS = {
  'v-app': { template: '<div><slot/></div>' },
  'v-container': { template: '<div><slot/></div>' },
  'v-img': { template: '<div><slot/></div>' },
  'v-row': { template: '<div><slot/></div>' },
  'v-col': { template: '<div><slot/></div>' },
  'v-card': { template: '<div><slot/></div>' },
  'v-card-title': { template: '<div><slot/></div>' },
  'v-card-text': { template: '<div><slot/></div>' },
  'v-form': { template: '<form><slot/></form>' },
  'v-text-field': { template: '<input />' },
  'v-btn': { template: '<button><slot/></button>' },
  'v-alert': { template: '<div><slot/></div>' },
  'v-divider': { template: '<hr />' },
  'v-list': { template: '<div><slot/></div>' },
  'v-list-item': { template: '<div><slot/></div>' },
  'v-list-item-title': { template: '<div><slot/></div>' },
  'v-list-item-subtitle': { template: '<div><slot/></div>' },
  'v-chip-group': { template: '<div><slot/></div>' },
  'v-chip': { template: '<div><slot/></div>' },
}
