<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251122124001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE connection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_station VARCHAR(10) NOT NULL, child_station VARCHAR(10) NOT NULL, distance DOUBLE PRECISION NOT NULL, network_name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_parent_station ON connection (parent_station)');
        $this->addSql('CREATE INDEX idx_child_station ON connection (child_station)');
        $this->addSql('CREATE TABLE route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_station_id VARCHAR(10) NOT NULL, to_station_id VARCHAR(10) NOT NULL, analytic_code VARCHAR(50) NOT NULL, distance_km DOUBLE PRECISION NOT NULL, path JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytic_code ON route (analytic_code)');
        $this->addSql('CREATE INDEX idx_analytic_created ON route (analytic_code, created_at)');
        $this->addSql('CREATE INDEX idx_created_at ON route (created_at)');
        $this->addSql('CREATE TABLE station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_name VARCHAR(10) NOT NULL, long_name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F39F8B13EE4B093 ON station (short_name)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE connection');
        $this->addSql('DROP TABLE route');
        $this->addSql('DROP TABLE station');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
