/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Login: typeof import('./components/Login.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RouteCalculator: typeof import('./components/RouteCalculator.vue')['default']
    RouteResult: typeof import('./components/RouteResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsForm: typeof import('./components/StatsForm.vue')['default']
    StatsTable: typeof import('./components/StatsTable.vue')['default']
    StatsView: typeof import('./components/StatsView.vue')['default']
  }
}
